# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampling <- function(x, s, NT, nthin, nupd, Nburn, g, nu_g, tausq_g, delta, beta_delta, sigma0sq, beta0, sigma1sq, beta1, z, gammam, clu, beta_pi, alpha_lambda, g_seq, delta_seq, sigma0sq_seq, sigma1sq_seq, z_seq, c_seq, gamma_seq, beta_pi_seq, alpha_lambda_seq, nu_g_seq, tausq_g_seq, beta_delta_seq, beta0_seq, beta1_seq, llambda, lpi, lobs, lother, lpost, m_g, dsq_g, a_g, b_g, alpha_delta, alpha0, alpha1, a_l, b_l, nu1, tau1sq, nu2, tau2sq, alpha_pi) {
    invisible(.Call('_BasClu_sampling', PACKAGE = 'BasClu', x, s, NT, nthin, nupd, Nburn, g, nu_g, tausq_g, delta, beta_delta, sigma0sq, beta0, sigma1sq, beta1, z, gammam, clu, beta_pi, alpha_lambda, g_seq, delta_seq, sigma0sq_seq, sigma1sq_seq, z_seq, c_seq, gamma_seq, beta_pi_seq, alpha_lambda_seq, nu_g_seq, tausq_g_seq, beta_delta_seq, beta0_seq, beta1_seq, llambda, lpi, lobs, lother, lpost, m_g, dsq_g, a_g, b_g, alpha_delta, alpha0, alpha1, a_l, b_l, nu1, tau1sq, nu2, tau2sq, alpha_pi))
}

